### ISSUE TITLE
Feature request - ability to control rotation of confetti

### ISSUE THREAD

**Issue by novemberkilo** [AlirezaHadjar/react-native-fast-confetti#4]
Hi, thanks for this library. I'm varying the confetti as I use it in my app (by playing around with the `colors` and `verticalSpacing` props). I'd love to increase the variability by also adjusting the way the confetti rotates. Would you be open to a prop that also allows rotation to be controlled?

Thanks.

**Comment by AlirezaHadjar** [comment]
Hey @novemberkilo, I’m currently using `Math.random` to randomize the rotation amount and direction of the confetti flakes. Could you clarify what exactly you have in mind?

Here’s the relevant code for reference:

```ts
export const getRandomBoolean = () => {
  'worklet';
  return Math.random() >= 0.5;
};

export const getRandomValue = (min: number, max: number): number => {
  'worklet';
  return Math.random() * (max - min) + min;
};

const clockwise = getRandomBoolean();
const maxRotation = {
  x: getRandomValue(2 * Math.PI, 20 * Math.PI),
  z: getRandomValue(2 * Math.PI, 20 * Math.PI),
};
const initialRotation = getRandomValue(0.1 * Math.PI, Math.PI);
```

Which properties would you like to control? If you need control over each property for individual flakes, you’ll need to pass an array, as each confetti flake will have its own configuration.

Let me know your thoughts! 🚀

**Comment by novemberkilo** [comment]
Thanks for the quick reply @AlirezaHadjar 

Perhaps I should have lead with the outcome I am looking to achieve - my app uses confetti to celebrate the completion of a task. I would like to vary the confetti so that the user continues to notice it (working with the principle that without sufficient variation the user will cease to notice it after a while). 

At the moment I am able to achieve this to some extent by randomly setting colours and verticalSpacing. I am curious to understand if I can add other variability (causing swirls or other randomness) and thus asked if we could control rotation. It looks like you are already randomising this.

Do you have any suggestions for how I can achieve more variability? Thank you.

**Comment by AlirezaHadjar** [comment]
Since I’m randomizing the rotation amount and direction, the only other tweaks I can think of are adjusting `flakeSize`, `colors`, or `verticalSpacing`. Let me know if those don’t do the trick!

**Comment by AlirezaHadjar** [comment]
Hey @novemberkilo 👋 
I’ve added a `sizeVariation` prop that allows you to add more randomness to the size of the confetti flakes. I'm gonna close this ticket. However, feel free to reopen it if you think there’s anything still missing.

**Comment by novemberkilo** [comment]
Thank you @AlirezaHadjar
