### ISSUE TITLE
[WEB] Confetti does not take full width on 2k screens.

### ISSUE THREAD

**Issue by JeanDes-Code** [AlirezaHadjar/react-native-fast-confetti#5]
### Issue Description:
When building a web app with React Native Expo and displaying it on a 2K window screen, the confetti generated by the react-`native-fast-confetti` library does not stretch to the full width of the screen. This results in a visual inconsistency where the confetti appears constrained.

### Steps to Reproduce:

1. Create a project using expo-router and Expo SDK 52 (also tested on SDK 51.0.32 with the same issue).
2. Install `react-native-reanimated` and `@shopify/react-native-skia`.
3. Run it on web `yarn start` + `w`.
4. Display the app on a screen with a 2K resolution.
5. Trigger the confetti animation.

### Expected Behavior:
The confetti should cover the full width of the screen, regardless of screen resolution.

### Actual Behavior:
The confetti does not span the full width of the screen on higher resolutions like 2K.

### Reproduction Repo:

I have created a minimal reproducible example showcasing this issue. 

- Basically an app created with `npx create-expo-app@latest`
- Installed `react-native-reanimated` [following the expo doc](https://docs.expo.dev/versions/latest/sdk/reanimated/).
- Installed `@shopify/react-native-skia` [following this doc](https://shopify.github.io/react-native-skia/docs/getting-started/installation).
- Configured skia for web [following this doc](https://shopify.github.io/react-native-skia/docs/getting-started/web).

You can find [the repository here](https://github.com/JeanDes-Code/reproduce-confetti-issue).

### Screenshot:
Here is a screenshot illustrating the issue:
![Capture d'écran 2024-12-19 160940](https://github.com/user-attachments/assets/ed02c3ca-bae3-40ad-8465-507f7fc15688)

### Environment:

- Library version: `react-native-fast-confetti` (`0.6.1`)
- Expo SDK: `52.0.20` (and `51.0.32`)
- Platform: Web (can't test on a 2k mobile screen 😅)
- Framework: `expo-router`

If there are any additional configurations or adjustments I should try to resolve this, please let me know. I’d be happy to provide more information or assist with testing.

Thank you!

**Comment by AlirezaHadjar** [comment]
Hey @JeanDes-Code sorry for the delay. Thank you for providing a detailed repro, it was really helpful. I've fixed the issue in `v0.7.0`. Feel free to reopen the ticket if you find any issues.
